# Site settings
title: Where Ideas Turn into Impact
description: One Stop Solution for All Your Content Writing Needs

# Set your production URL (works for both local and GitHub Pages)
# For custom domain:
url: "https://tecofers.com"
# For GitHub Pages default domain, comment above line and uncomment below:
# url: "https://tecofers.github.io"
baseurl: "" # Leave empty for custom domain; set to "/repo-name" if not using custom domain

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Social links
facebook_username: aliimran.nagori
twitter_username: AliImranMuneeri
linkedin_username: ali-imran-nagori

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Default categories
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Admin"
  -
    scope:
      path: "categories"
    values:
      layout: "blog"
