# Site settings
title: Where Ideas Turn into Impact
description: One Stop Solution for All Your Content Writing Needs
baseurl: "" # the subpath of your site
url: "tecofers.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Social links
facebook_username: aliimran.nagori
twitter_username: AliImranMuneeri
linkedin_username: ali-imran-nagori

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - restaurant/
#favicon: "/favicon.ico"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
# Default categories
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Admin"
  -
    scope:
      path: "categories"
    values:
      layout: "blog"
