- title: Technical Writing
  icon: bi-code-square
  description: Professional technical documentation, API guides, user manuals, and software documentation.
  url: /services/technical-writing

- title: Medical Content
  icon: bi-heart-pulse
  description: Research papers, medical blogs, healthcare documentation, and clinical content writing.
  url: /services/medical-writing

- title: Blog Writing
  icon: bi-pencil-square
  description: SEO-optimized blog posts, articles, and content marketing materials.
  url: /services/blog-writing

- title: Academic Writing
  icon: bi-book
  description: Research papers, thesis writing, academic articles, and educational content.
  url: /services/academic-writing

- title: Marketing Copy
  icon: bi-megaphone
  description: Website content, sales copy, email campaigns, and marketing materials.
  url: /services/marketing-copy

- title: SEO Content
  icon: bi-graph-up
  description: Search engine optimized content, keyword research, and meta descriptions.
  url: /services/seo-content